##
##    !! WARNING !!  Ansible only interprets 'True' and 'False'
##                   as booleans when reading ini files.  Other
##                   values such as 'true' or 'false' would be 
##                   interpreted as strings and would break various
##                   logic tests.  
##
##                   When reading YML files, booleans can take on
##                   many forms and be interpreted correctly.
##
##                   For consistency, only use unquoted booleans: True & False

all: 

  vars:

    ## ----------------------------------------
    ##    Workshop Variables

    workshop_vars:

      clustername:         "{{ lookup('file','.././config/gpte-guid.txt') }}"
      network_basedomain:  "internal"
      network_fqdn:        "{{ lookup('file','.././config/gpte-guid.txt') }}.internal"
      
#      network_network:     "192.168.1.0"
#      network_netmask:     "255.255.255.0"
#      network_broadcast:   "192.168.1.255"
#      network_prefix:      "24"
#      network_gateway:     "192.168.1.1"
#      network_nameserver:  "192.168.1.30"
#      network_timeserver:  "192.168.1.60"
      
      studentName:         "cloud-user"

    ## ----------------------------------------
    ##    Xtoph Deploy Variables

#    xtoph_vars:
#
#      deployhost_ip:       "192.168.1.170" 
#      clustername:         "{{ workshop_vars.clustername }}"

    ## ----------------------------------------
    ##    Override default ansible host with
    ##    one that includes fqdn.  This saves us
    ##    from having to specify FQDN in host 
    ##    vars section below.  This assumes all
    ##    hosts are in the same domain. DUH!

    ansible_host: "{{ inventory_hostname }}.{{ workshop_vars.network_fqdn }}"



## ----------------------------------------
## HOSTGROUPS & VARS
## ----------------------------------------



#myDeployhost:
#  hosts:
#    deployer:
#      h_pubIP: "{{ xtoph_vars.deployhost_ip }}"
#  vars:
#    ansible_connection: local



## -----------------



myBastion:
  hosts:
    bastion:
  vars:
    ansible_connection: local



## -----------------



myNodes:
  hosts:
    node1:
    node2:
    node3:
    node4:
