---
- hosts: node2
  become: true
  tasks:
  
    - name: "rhel8-unit-stratis : yum install packages"
      yum: name=stratisd,stratis-cli state=installed
      register: result
      retries: 10
      until: result is succeeded
      delay: 5
      
    - name: "rhel8-unit-stratis : service restart"
      service: name="stratisd" state=restarted enabled=yes

    - name: "rhel8-unit-stratis : cheat file installs"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-checkhost.j2', dest: '/usr/local/bin/cheat-stratis-checkhost.sh'} 
        - {src: 'cheat-stratis-fstab.j2', dest: '/usr/local/bin/cheat-stratis-fstab.sh'} 
